In [9]:
import random
x=random.randint(1,10)
print(x)

9


In [28]:
from numpy import random
x=random.choice([3,5,7,9],p=[0.1,0.4,0.3,0.2],size=(100))
x

array([7, 7, 5, 7, 5, 3, 5, 5, 7, 5, 7, 9, 7, 5, 5, 9, 5, 9, 3, 5, 5, 3,
       7, 7, 7, 3, 7, 5, 5, 5, 5, 7, 7, 5, 7, 9, 9, 5, 9, 5, 5, 5, 3, 7,
       5, 5, 5, 7, 9, 7, 5, 7, 7, 5, 3, 5, 3, 7, 3, 3, 5, 9, 7, 3, 9, 9,
       3, 5, 9, 5, 9, 5, 7, 9, 5, 7, 3, 7, 9, 3, 9, 7, 7, 3, 3, 7, 5, 5,
       7, 9, 5, 9, 7, 3, 5, 5, 3, 5, 5, 9])

In [29]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[3 5 4 1 2]


In [30]:
 from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[3 4 1 5 2]


In [31]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [41]:
import numpy as np
def ad(a,b):
    return a+b

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
ad = np.frompyfunc(ad,2, 1)

print(ad(x,y))

[5 7 9 11]
