### Matrix Operations

In [2]:
import numpy as np

In [3]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
res=np.add(a1,a2)
res

array([ 7,  9, 11, 13, 15])

In [4]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
res=np.add(a1,10)
res

array([11, 12, 13, 14, 15])

In [6]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
res=np.multiply(a1,a2)
res

array([ 6, 14, 24, 36, 50])

### Math Operations

In [8]:
a1=np.array([1.4,6.5,9.8,4.5,6.7])
res=np.floor(a1)
res

array([1., 6., 9., 4., 6.])

In [9]:
a1=np.array([1.4,6.5,9.8,4.5,6.7])
res=np.ceil(a1)
res

array([ 2.,  7., 10.,  5.,  7.])

In [11]:
a1=np.array([1.446541,6.56546,9.855644,4.535659,6.7566562])
res=np.around(a1,decimals=2)
res

array([1.45, 6.57, 9.86, 4.54, 6.76])

In [12]:
a1=np.array([1,2,3,4,5,6,7,8,9])
res=np.sqrt(a1)
res

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
a1=np.array([1,2,3,4,5,6,7,8,9])
res=np.cbrt(a1)
res

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059, 1.91293118, 2.        , 2.08008382])

In [14]:
a1=np.array([1,2,3,4,5,6,7,8,9])
res=np.mean(a1)
res

5.0

In [15]:
a1=np.array([1,2,7,4,5,4,7,2,9])
res=np.median(a1)
res

4.0

In [21]:
data={'cgpa':[1,2,np.nan,4,5,1000],'present':[1,0,1,np.nan,1,0],'package':[1,2,np.nan,4,5,6]}
data

{'cgpa': [1, 2, nan, 4, 5, 1000],
 'present': [1, 0, 1, nan, 1, 0],
 'package': [1, 2, nan, 4, 5, 6]}

In [22]:
import pandas as pd
df=pd.DataFrame(data)
df

cgpa  present  package
0     1.0      1.0      1.0
1     2.0      0.0      2.0
2     NaN      1.0      NaN
3     4.0      NaN      4.0
4     5.0      1.0      5.0
5  1000.0      0.0      6.0

In [23]:
a1=np.array([1,2,3,4,5,6,7,8,9])
res=np.var(a1)
res

6.666666666666667

## Pandas

### used for data analysis and manipulation

### Use Case:

- Read csv,excel and json
- EDA (exploratory data analysis)
- Data Cleaning
- missing values
- ouliers
- Encoding             -1 One hot encoding  -2 Label encoding
- Feature Selection
- Join Multiple Columns

- Array
- Dict
- List
- tuple
- Read csv,excel

In [26]:
import numpy as np 
import pandas as pd

a1=np.random.randint(21,100,size=(10,4))
df=pd.DataFrame(a1)
df

0   1   2   3
0  95  94  79  51
1  60  72  40  28
2  25  43  26  25
3  39  32  41  68
4  52  61  52  80
5  52  60  48  84
6  43  65  38  41
7  48  29  33  35
8  34  30  64  98
9  34  60  56  48

In [5]:
import numpy as np 
import pandas as pd
data={'zeros':np.zeros(10,dtype=int),
     'ones':np.ones(10,dtype=int),
     'full':np.full(10,8),
     'list':np.random.randint(21,100,size=(10)),
     'tuple':(11,12,13,14,15,16,17,18,19,20),
     'random':np.random.randint(10,51,size=10)}
df=pd.DataFrame(data)
df

zeros  ones  full  list  tuple  random
0      0     1     8    56     11      14
1      0     1     8    51     12      25
2      0     1     8    86     13      50
3      0     1     8    79     14      42
4      0     1     8    27     15      25
5      0     1     8    72     16      35
6      0     1     8    23     17      27
7      0     1     8    49     18      38
8      0     1     8    67     19      28
9      0     1     8    86     20      50

In [3]:
import pandas as pd
df=pd.read_csv("data/Iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]